### ISSUE TITLE
Compatible with BepInEx6

### ISSUE THREAD

**Issue by SuperYYT** [Cities2Modding/FirstPersonCamera#1]
Some modules only support BepInEx6. Is it possible to build another version of BepInEx6 to give one more choice~

**Comment by optimus-code** [comment]
The project is buildable in BepInEx6 using the compiler directives. Currently we are not distributing version 6 as it's not LTS and not supported by Thunderstore.io. 

Also be wary, some of those BepInEx6 mods may be ones compiled by the fake Paradox modding site. Anything you download from that source is not supported by the mod authors. Content is stolen by that website, runtimes altered sometimes too. There are no guarantees of no malware etc if people use those sources.
